trigger:
- main

pool:
  name: Appium

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y tar
  displayName: 'Install tar utility'
  shell: bash

- task: UseNode@1
  displayName: 'Install Node.js'
  inputs:
    version: '16.x'

- script: |
    echo "Setting up environment"
    sudo apt-get install -y openjdk-11-jdk curl unzip lib32stdc++6 lib32z1
  displayName: 'Install Dependencies'
  shell: bash

- script: |
    echo "Running Tests"
    appium --log-level debug &
    npx mocha ./test/ui_tests.js
  displayName: 'Run UI Tests'
  shell: bash
